// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'firewall_rule.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FirewallRule _$FirewallRuleFromJson(Map<String, dynamic> json) => FirewallRule(
  uuid: json['uuid'] as String,
  type: json['type'] as String,
  interfaceName: json['interface'] as String,
  protocol: json['protocol'] as String,
  source: json['source'] as String,
  destination: json['destination'] as String,
  sourcePort: json['source_port'] as String? ?? '',
  destinationPort: json['destination_port'] as String,
  description: json['descr'] as String,
  enabled: json['enabled'] as String,
  sequence: (json['sequence'] as num).toInt(),
  origin: json['origin'] as String? ?? '',
  direction: json['direction'] as String? ?? 'in',
  ipProtocol: json['ipprotocol'] as String? ?? 'inet',
  quick: json['quick'] as String? ?? '1',
  sourceNot: json['source_not'] as String? ?? '0',
  destinationNot: json['destination_not'] as String? ?? '0',
  log: json['log'] as String? ?? '0',
  stateType: json['statetype'] as String? ?? 'keep',
  categories:
      (json['categories'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList() ??
      [],
  interfaceNot: json['interfacenot'] as String? ?? '0',
  noSync: json['nosync'] as String? ?? '0',
  sortOrder: json['sort_order'] as String? ?? '',
  allowOpts: json['allowopts'] as String? ?? '0',
  tcpFlags1:
      (json['tcpflags1'] as List<dynamic>?)?.map((e) => e as String).toList() ??
      [],
  tcpFlags2:
      (json['tcpflags2'] as List<dynamic>?)?.map((e) => e as String).toList() ??
      [],
  tcpFlagsAny: json['tcpflags_any'] as String? ?? '0',
  schedule: json['sched'] as String? ?? '',
  divertTo: json['divert-to'] as String? ?? '',
  gateway: json['gateway'] as String? ?? '',
  replyTo: json['replyto'] as String? ?? '',
  disableReplyTo: json['disablereplyto'] as String? ?? '0',
  statePolicy: json['state-policy'] as String? ?? '',
  noPfsync: json['nopfsync'] as String? ?? '0',
  statTimeout: json['statetimeout'] as String? ?? '',
  udpFirst: json['udp-first'] as String? ?? '',
  udpSingle: json['udp-single'] as String? ?? '',
  udpMultiple: json['udp-multiple'] as String? ?? '',
  adaptiveStart: json['adaptivestart'] as String? ?? '',
  adaptiveEnd: json['adaptiveend'] as String? ?? '',
  max: json['max'] as String? ?? '',
  maxSrcNodes: json['max-src-nodes'] as String? ?? '',
  maxSrcStates: json['max-src-states'] as String? ?? '',
  maxSrcConn: json['max-src-conn'] as String? ?? '',
  maxSrcConnRate: json['max-src-conn-rate'] as String? ?? '',
  maxSrcConnRates: json['max-src-conn-rates'] as String? ?? '',
  overload: json['overload'] as String? ?? '',
  shaper1: json['shaper1'] as String? ?? '',
  shaper2: json['shaper2'] as String? ?? '',
  prio: json['prio'] as String? ?? '',
  setPrio: json['set-prio'] as String? ?? '',
  setPrioLow: json['set-prio-low'] as String? ?? '',
  tos: json['tos'] as String? ?? '',
  tag: json['tag'] as String? ?? '',
  tagged: json['tagged'] as String? ?? '',
);

Map<String, dynamic> _$FirewallRuleToJson(FirewallRule instance) =>
    <String, dynamic>{
      'uuid': instance.uuid,
      'type': instance.type,
      'interface': instance.interfaceName,
      'protocol': instance.protocol,
      'source': instance.source,
      'destination': instance.destination,
      'source_port': instance.sourcePort,
      'destination_port': instance.destinationPort,
      'descr': instance.description,
      'enabled': instance.enabled,
      'sequence': instance.sequence,
      'origin': instance.origin,
      'direction': instance.direction,
      'ipprotocol': instance.ipProtocol,
      'quick': instance.quick,
      'source_not': instance.sourceNot,
      'destination_not': instance.destinationNot,
      'log': instance.log,
      'statetype': instance.stateType,
      'categories': instance.categories,
      'interfacenot': instance.interfaceNot,
      'nosync': instance.noSync,
      'sort_order': instance.sortOrder,
      'allowopts': instance.allowOpts,
      'tcpflags1': instance.tcpFlags1,
      'tcpflags2': instance.tcpFlags2,
      'tcpflags_any': instance.tcpFlagsAny,
      'sched': instance.schedule,
      'divert-to': instance.divertTo,
      'gateway': instance.gateway,
      'replyto': instance.replyTo,
      'disablereplyto': instance.disableReplyTo,
      'state-policy': instance.statePolicy,
      'nopfsync': instance.noPfsync,
      'statetimeout': instance.statTimeout,
      'udp-first': instance.udpFirst,
      'udp-single': instance.udpSingle,
      'udp-multiple': instance.udpMultiple,
      'adaptivestart': instance.adaptiveStart,
      'adaptiveend': instance.adaptiveEnd,
      'max': instance.max,
      'max-src-nodes': instance.maxSrcNodes,
      'max-src-states': instance.maxSrcStates,
      'max-src-conn': instance.maxSrcConn,
      'max-src-conn-rate': instance.maxSrcConnRate,
      'max-src-conn-rates': instance.maxSrcConnRates,
      'overload': instance.overload,
      'shaper1': instance.shaper1,
      'shaper2': instance.shaper2,
      'prio': instance.prio,
      'set-prio': instance.setPrio,
      'set-prio-low': instance.setPrioLow,
      'tos': instance.tos,
      'tag': instance.tag,
      'tagged': instance.tagged,
    };

FirewallRuleRequest _$FirewallRuleRequestFromJson(Map<String, dynamic> json) =>
    FirewallRuleRequest(
      type: json['action'] as String,
      interfaceName: json['interface'] as String,
      protocol: json['protocol'] as String,
      source: json['source_net'] as String,
      destination: json['destination_net'] as String,
      destinationPort: json['destination_port'] as String,
      description: json['description'] as String,
      enabled: json['enabled'] as String? ?? '1',
      sourceNot: json['source_not'] as String? ?? '0',
      destinationNot: json['destination_not'] as String? ?? '0',
      ipProtocol: json['ipprotocol'] as String? ?? 'inet',
      direction: json['direction'] as String? ?? 'in',
      quick: json['quick'] as String? ?? '1',
      sourcePort: json['source_port'] as String? ?? '',
      log: json['log'] as String? ?? '0',
      stateType: json['statetype'] as String? ?? 'keep',
      interfaceNot: json['interfacenot'] as String? ?? '0',
      noSync: json['nosync'] as String? ?? '0',
      sequence: json['sequence'] as String? ?? '',
      allowOpts: json['allowopts'] as String? ?? '0',
      tcpFlagsAny: json['tcpflags_any'] as String? ?? '0',
      schedule: json['sched'] as String? ?? '',
      divertTo: json['divert-to'] as String? ?? '',
      gateway: json['gateway'] as String? ?? '',
      replyTo: json['replyto'] as String? ?? '',
      disableReplyTo: json['disablereplyto'] as String? ?? '0',
      statePolicy: json['state-policy'] as String? ?? '',
      noPfsync: json['nopfsync'] as String? ?? '0',
      statTimeout: json['statetimeout'] as String? ?? '',
      udpFirst: json['udp-first'] as String? ?? '',
      udpSingle: json['udp-single'] as String? ?? '',
      udpMultiple: json['udp-multiple'] as String? ?? '',
      adaptiveStart: json['adaptivestart'] as String? ?? '',
      adaptiveEnd: json['adaptiveend'] as String? ?? '',
      max: json['max'] as String? ?? '',
      maxSrcNodes: json['max-src-nodes'] as String? ?? '',
      maxSrcStates: json['max-src-states'] as String? ?? '',
      maxSrcConn: json['max-src-conn'] as String? ?? '',
      maxSrcConnRate: json['max-src-conn-rate'] as String? ?? '',
      maxSrcConnRates: json['max-src-conn-rates'] as String? ?? '',
      overload: json['overload'] as String? ?? '',
      shaper1: json['shaper1'] as String? ?? '',
      shaper2: json['shaper2'] as String? ?? '',
      prio: json['prio'] as String? ?? '',
      setPrio: json['set-prio'] as String? ?? '',
      setPrioLow: json['set-prio-low'] as String? ?? '',
      tos: json['tos'] as String? ?? '',
      tag: json['tag'] as String? ?? '',
      tagged: json['tagged'] as String? ?? '',
      categories:
          (json['categories'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
    );

Map<String, dynamic> _$FirewallRuleRequestToJson(
  FirewallRuleRequest instance,
) => <String, dynamic>{
  'action': instance.type,
  'interface': instance.interfaceName,
  'protocol': instance.protocol,
  'source_net': instance.source,
  'source_not': instance.sourceNot,
  'destination_net': instance.destination,
  'destination_not': instance.destinationNot,
  'destination_port': instance.destinationPort,
  'description': instance.description,
  'enabled': instance.enabled,
  'source_port': instance.sourcePort,
  'log': instance.log,
  'ipprotocol': instance.ipProtocol,
  'direction': instance.direction,
  'quick': instance.quick,
  'statetype': instance.stateType,
  'interfacenot': instance.interfaceNot,
  'nosync': instance.noSync,
  'sequence': instance.sequence,
  'allowopts': instance.allowOpts,
  'tcpflags_any': instance.tcpFlagsAny,
  'sched': instance.schedule,
  'divert-to': instance.divertTo,
  'gateway': instance.gateway,
  'replyto': instance.replyTo,
  'disablereplyto': instance.disableReplyTo,
  'state-policy': instance.statePolicy,
  'nopfsync': instance.noPfsync,
  'statetimeout': instance.statTimeout,
  'udp-first': instance.udpFirst,
  'udp-single': instance.udpSingle,
  'udp-multiple': instance.udpMultiple,
  'adaptivestart': instance.adaptiveStart,
  'adaptiveend': instance.adaptiveEnd,
  'max': instance.max,
  'max-src-nodes': instance.maxSrcNodes,
  'max-src-states': instance.maxSrcStates,
  'max-src-conn': instance.maxSrcConn,
  'max-src-conn-rate': instance.maxSrcConnRate,
  'max-src-conn-rates': instance.maxSrcConnRates,
  'overload': instance.overload,
  'shaper1': instance.shaper1,
  'shaper2': instance.shaper2,
  'prio': instance.prio,
  'set-prio': instance.setPrio,
  'set-prio-low': instance.setPrioLow,
  'tos': instance.tos,
  'tag': instance.tag,
  'tagged': instance.tagged,
  'categories': instance.categories,
};
